- create form template
- each form as typed fields with type, name, required
- fields grouped by section or not
- section can be a part of an other section
- delete / restore items (section and fields)